name: Create and publish Packages

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: ${{ github.repository }}
  IMAGE_REGISTRY: ghcr.io
  REGISTRY_USER: ${{ github.actor }}
  REGISTRY_PASSWORD: ${{ github.token }}

jobs:
  create-and-publish-packages:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@40891eba8c2bcd1309b07ba8b11232f313e86779
        with:
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}

      - name: Build packager
        uses: docker/build-push-action@91df6b874e498451163feb47610c87c4a218c1ee
        with:
          context: .
          target: packager
          load: true
          tags: packager

      - name: Extract built package
        run: |
          ID=$(docker create packager)
          docker cp $ID:/opt/slurm.tar.gz .
          docker rm $ID
      
      - name: Upload package
        uses: actions/upload-artifact@v2
        with:
          name: slurm
          path: slurm.tar.gz

      - name: Extract metadata (tags, labels) for slurmctld
        id: slurmctld-meta
        uses: docker/metadata-action@c4ee3adeed93b1fa6a762f209fb01608c1a22f1e
        with:
          images: ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}
          flavor: slurmctld

      - name: Build and push slurmctld image
        uses: docker/build-push-action@91df6b874e498451163feb47610c87c4a218c1ee
        with:
          context: .
          target: slurmctld
          push: true
          build-args: |
            DOCKER_METADATA_OUTPUT_JSON
          tags: ${{ steps.slurmctld-meta.outputs.tags }}
          labels: ${{ steps.slurmctld-meta.outputs.labels }}